config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tasks

  resources :user_stories do
    resources :user_story_files
  end 

  get 'projects/index'

  get 'projects/user_stories/show/:id' =>'user_stories#show'
  get 'projects/user_stories/new/:project_id' =>'user_stories#new'
  get 'productsjects/user_stories/show/tasks/:user_story_id' => 'tasks#new'
  get '/user_stories/tasks/:user_story_id' => 'tasks#new'

  patch '/user_stories/change_state/:id' => 'user_stories#changestate', as: "changestate" 

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :project_users
  resources :users
  resources :projects 
  root 'projects#index' , as: 'login'

  post 'projects/add_members' =>'projects#add_members'

  post 'user_stories/add_comment' =>'user_stories#add_comment' , as: 'add_comment'

  post 'project/comment' => 'projects#comment' , as: 'comments'

  get 'project/show_comments' => 'projects#show_comment' , as: 'show_comments'
  get 'project/deliver' => 'projects#deliver' , as: 'deliver'

end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
	belongs_to :project
	has_many :user_story_files
	has_many :tasks, dependent: :destroy
	has_many :user_comments, dependent: :destroy
	has_many :user_story_members 
	has_many :users , through: :user_story_members, dependent: :destroy
	accepts_nested_attributes_for :tasks
	enum state: [:to_be_do, :doing, :done]
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :set_user_story, only: [ :show,:edit, :update, :destroy, :changestate , :add_comment]

  # GET /user_stories
  # GET /user_stories.json
  def index
    @user_stories = UserStory.all
  end

  # GET /user_stories/1
  # GET /user_stories/1.json
  def show
    @project_id=@user_story.project_id
    @member = current_user.members.where(project_id: @project_id).last
    @all_members = @user_story.users
    @comments=@user_story.user_comments 
  end

  def add_comment
    UserComment.create(content: params[:post_comment], user_id: current_user.id,user_story_id: params[:id],username: current_user.username)
    redirect_to user_story_url(@user_story.id)
  end

  
  # GET /user_stories/new
  def new
    #TODO project.user_story.new
    @user_story = UserStory.new
    @user_story.project_id = params[:project_id]
    @user_ids=Member.select(:user_id).where(project_id: @user_story.project_id)
    @users=User.where(id: @user_ids)
    @story_member=@user_story.user_story_members.build
  end

  # GET /user_stories/1/edit
  def edit
    @user_ids=UserStoryMember.select(:user_id).where(user_story_id: @user_story.id)
    @users=User.where("id NOT IN (?)" , @user_ids)
    @story_member=@user_story.user_story_members.build
  end

  # POST /user_stories
  # POST /user_stories.json
  def create
    @user_story = UserStory.new(user_story_params)
    params[:user][:id].each do |user|
      if !user.empty?
        @user_story.user_story_members.build(:user_id => user)
      end
    end
    @current_project = Project.find_by_id(params[:user_story][:project_id])
    @current_project.user_stories << @user_story
    respond_to do |format|
      if @user_story.save
        format.html { redirect_to @current_project, notice: 'User story was successfully created.' }
        format.json { render :show, status: :created, location: @user_story }
      else
        format.html { render :new }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stories/1
  # PATCH/PUT /user_stories/1.json
  def update
    params[:user][:id].each do |user|
      if !user.empty?
        @user_story.user_story_members.build(:user_id => user)
      end
    end
    respond_to do |format|
      if @user_story.update(user_story_params)
        puts params.require(:user_story)[:state]
        @user_story.state = params.require(:user_story)[:state]
        format.html { redirect_to @user_story, notice: 'User story was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @user_story }
      else
        format.html { render :edit }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  def changestate
    respond_to do |format|
      if @user_story.update(user_story_params)
        puts params.require(:user_story)[:state]
        @user_story.state = params.require(:user_story)[:state]
        format.html { redirect_to @user_story, notice: 'User story was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @user_story }
      else
        format.html { render :edit }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end   
  end

  # DELETE /user_stories/1
  # DELETE /user_stories/1.json
  def destroy
    @user_story.destroy
    respond_to do |format|
      format.html { redirect_to user_stories_url, notice: 'User story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_story_params
      params.require(:user_story).permit(:name, :descp, :state, :project_id)
    end
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/user_stories/_comments.html.haml
-if @comments!=nil
	-@comments.each do |comment|
		=comment.username
		= " :  "
		=comment.content
		%br

app/views/user_stories/_form.html.haml
%center
  .well.halfPageWidth
    = form_for @user_story, html: { class: "form form-horizontal project" } do |f|
      - if @user_story.errors.any?
        #error_explanation
          %h2= "#{pluralize(@user_story.errors.count, "error")} prohibited this user_story from being saved:"
          %ul
            - @user_story.errors.full_messages.each do |msg|
              %li= msg

      = f.hidden_field :project_id, value: @user_story.project_id
      
      %center
        .field
          = f.text_field :name, class: 'form-control formElement', required: true, placeholder: 'User Story Name'
        .field
          = f.text_area :descp, class: 'form-control formElement', required: true, placeholder: 'User Story Description'
        .field
          = f.select :state, ["to_be_do", "doing", "done"], class: 'form-control formElement', required: true, placeholder: 'State'
        = fields_for(@story_member) do |m|
          .field
            = m.label "Add members"
            %br
              = collection_select(:user , :id , @users , :id , :username ,{}, {:multiple => true })
            %br
        .actions
          = f.submit nil,class: 'btn btn-primary'
          = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/user_stories/edit.html.haml
%h1 Editing user_story

= render 'form'

= link_to 'Show', @user_story
\|
= link_to 'Back', user_stories_path

app/views/user_stories/index.html.haml
%h1 Listing user_stories

%table
  %tr
    %th Name
    %th Descp
    %th State
    %th
    %th
    %th

  - @user_stories.each do |user_story|
    %tr
      %td= user_story.name
      %td= user_story.descp
      %td= user_story.state
      %td= link_to 'Show', user_story
      %td= link_to 'Edit', edit_user_story_path(user_story)
      %td= link_to 'Destroy', user_story, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User story', new_user_story_path

app/views/user_stories/new.html.haml
%h1 New user_story

= render 'form'

= link_to 'Back', user_stories_path

app/views/user_stories/show.html.haml
%p
	%h1= @user_story.name
%center
	.well.halfPageWidth
		%p
			%b Descp:
			= @user_story.descp
		%p
			%b State:
			= @user_story.state
		= link_to 'add File', new_user_story_user_story_file_path(@user_story)	
		|
		= link_to 'add Task', 'tasks/'+@user_story.id.to_s
		-if @member.owner==true
			|
			= link_to 'Edit', edit_user_story_path(@user_story)
		|
		= link_to 'Back', project_path(@project_id)
		%h5 Files attached for this User story:
		%ul
		- @user_story.user_story_files.each do |file|
			%li= file.document_file_name 


		%h5 Tasks for this User story:
		%ul
		- @user_story.tasks.each do |task|
			= form_for(task, remote: true) do |f|
				- if (task.state)
					%li.lineThrough 
						#{task.name}: #{f.check_box :state , class: 'state'}
						= link_to "delete task", task,:method=> "delete", :class => "btn btn-danger deleteTask", :remote=> true
				-else 
					%li
						#{task.name}: #{f.check_box :state , class: 'state'}
						= link_to "delete task", task,:method=> "delete", :class => "btn btn-danger deleteTask", :remote=> true

		%h5 All members:
		-@all_members.each do |member|
			.media
				%a.pull-left
					%img.media-object.profileAvatar{:src => "#{member.avatar.url(:thumb)}"}
				 
				= member.username
	.well.halfPageWidth
		= form_tag add_comment_path(:id => @user_story) , remote: true do
			%p
			= text_field_tag :post_comment, params[:post_comment]
			= submit_tag "comment", :name => nil 

		#comments
			=render('comments')

app/views/user_stories/show.js.erb
$("#comments").html("<%= escape_javascript(render("comments"))%>");