config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tasks

  resources :user_stories do
    resources :user_story_files
  end 

  get 'projects/index'

  get 'projects/user_stories/show/:id' =>'user_stories#show'
  get 'projects/user_stories/new/:project_id' =>'user_stories#new'
  get 'productsjects/user_stories/show/tasks/:user_story_id' => 'tasks#new'
  get '/user_stories/tasks/:user_story_id' => 'tasks#new'

  patch '/user_stories/change_state/:id' => 'user_stories#changestate', as: "changestate" 

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :project_users
  resources :users
  resources :projects 
  root 'projects#index' , as: 'login'

  post 'projects/add_members' =>'projects#add_members'

  post 'user_stories/add_comment' =>'user_stories#add_comment' , as: 'add_comment'

  post 'project/comment' => 'projects#comment' , as: 'comments'

  get 'project/show_comments' => 'projects#show_comment' , as: 'show_comments'
  get 'project/deliver' => 'projects#deliver' , as: 'deliver'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user_story
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.id = params[:user_story_id]
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @current_user_story = UserStory.find(params[:task][:user_story_id])
    @current_user_story.tasks << @task
    respond_to do |format|
      if @task.save
        format.html { redirect_to @current_user_story, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :state, :user_stories_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
%center
  .well.halfPageWidth
    = form_for @task, html: { class: "form form-horizontal project" } do |f|
      - if @task.errors.any?
        #error_explanation
          %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
          %ul
            - @task.errors.full_messages.each do |msg|
              %li= msg
      = f.hidden_field :user_story_id, value: @task.id
      .field
        = f.text_field :name, class: 'form-control formElement', required: true, placeholder: 'Task Name'
      .field
        = f.text_area :description, class: 'form-control formElement', required: true, placeholder: 'Task Description'
      .field
        = f.check_box :state, class: 'form-control formElement', required: true, placeholder: 'Task State'
      .actions
        = f.submit nil,class: 'btn btn-primary'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Name
    %th Description
    %th State
    %th User stories
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.name
      %td= task.description
      %td= task.state
      %td= task.user_story_id
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b State:
  = @task.state
%p
  %b User stories:
  = @task.user_story_id

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path