config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tasks

  resources :user_stories do
    resources :user_story_files
  end 

  get 'projects/index'

  get 'projects/user_stories/show/:id' =>'user_stories#show'
  get 'projects/user_stories/new/:project_id' =>'user_stories#new'
  get 'productsjects/user_stories/show/tasks/:user_story_id' => 'tasks#new'
  get '/user_stories/tasks/:user_story_id' => 'tasks#new'

  patch '/user_stories/change_state/:id' => 'user_stories#changestate', as: "changestate" 

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :project_users
  resources :users
  resources :projects 
  root 'projects#index' , as: 'login'

  post 'projects/add_members' =>'projects#add_members'

  post 'user_stories/add_comment' =>'user_stories#add_comment' , as: 'add_comment'

  post 'project/comment' => 'projects#comment' , as: 'comments'

  get 'project/show_comments' => 'projects#show_comment' , as: 'show_comments'
  get 'project/deliver' => 'projects#deliver' , as: 'deliver'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :members, dependent: :destroy
	belongs_to :user
	has_many :users , through: :members 
	has_many :user_stories , dependent: :destroy
	accepts_nested_attributes_for :user_stories

	def deliver
		sleep 5
		update_attribute(:name , "Projectt")
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	 before_action :set_project, only: [:show, :edit, :update, :destroy, :add_members , :deliver]
	 before_action :check , only: [:show, :edit, :update, :destroy]

	def check
		relation=Member.where(user_id: current_user.id,project_id: params[:id])
		
		puts relation
		
		if relation.empty?
			
			redirect_to projects_url, :notice => "There is no such a project"
		end
	end
	def index
		@users = User.all
		@search =  Project.search(params[:q])
		#@projects =Project.joins(:members).where(members: {user_id: current_user.id})
		@projects =@search.result
		@search.build_condition
	end


	def deliver
		@project=Project.find(params[:id])
		@project.delay.deliver
		redirect_to project_url(params[:id]) , notice: "Delviered"
	end

	def show
		#TODO fix relation 
		#current_user.projects.where(id: params[:project_id])
		@owner_check = false
		if(@project.user_id==current_user.id)
			@owner_check=true
		end
		@users=User.search(params[:members_search])
		@member=@project.members.build
#		params[:user][:id].each do |user|
#			if !user.empty?
#				@project.members.build(:user_id => user)
#			end
#		end
		@all_members = @project.users
  	end

  	def comment
    	#@comments = User.find(params[:user][:id]).user_comments
    	@comments=Project.joins(:user_stories => :user_comments).select('projects.name as "project",user_comments.content,user_stories.name').where('user_comments.user_id' => params[:user][:id])
  	end

  	def show_comment
  		 @comments=Project.joins(:user_stories => :user_comments).joins("LEFT JOIN `tasks` ON `tasks`.`user_story_id` = `user_stories`.`id`").select('projects.name as "project",user_comments.content,user_comments.username,user_stories.name,tasks.name as"task"')

  	end

	def new
		@project=Project.new
		#TODO remove member and make it by ajax
		@users=User.where.not(id: current_user.id)
		@member=@project.members.build
	end

	def edit
		#current_user.projects(id: params[:id])
		@user_ids=Member.select(:user_id).where(project_id: Project.find(params[:id]))
		#TODO
		@users=User.where("id NOT IN (?)" , @user_ids)
		@member=@project.members.build
  	end


	def create
		@project= Project.new(project_params)
		@project[:user_id]=current_user.id
#		params[:user][:id].each do |user|0
#			if !user.empty?
#				@project.members.build(:user_id => user)
#			end
#		end
	    respond_to do |format|
	      if @project.save
	      	@member = Member.new
			@member.user_id=current_user.id
			@member.project_id=@project.id
			@member.owner=1
			@member.save
	        format.html { redirect_to @project, notice: 'Project was successfully created.' }
	        format.json { render :show, status: :created, location: @project }
	      else
	        format.html { render :new }
	        format.json { render json: @product.errors, status: :unprocessable_entity }
	      end
	    end
	end


	def update

		params[:user][:id].each do |user|
			if !user.empty?
				@project.members.build(:user_id => user)
			end
		end
		respond_to do |format|
	      if @project.save
	        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
	        format.json { render :show, status: :created, location: @project }
	      else
	        format.html { render :new }
	        format.json { render json: @product.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def destroy
		@project.destroy
    	respond_to do |format|
      		format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      		format.json { head :no_content }
    	end
	end
	def add_members
		puts "================================================"
		puts params[:id]
		puts params[:user][:id]
		puts "================================================"
		test=Member.where(user_id: params[:user][:id],project_id:params[:id])
		if test.empty?
			Member.create(user_id: params[:user][:id], project_id: params[:id])
		end
		redirect_to projects_url
	end
	private
    # Use callbacks to share common setup or constraints between actions.
	    def set_project
	      @project = Project.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def project_params
	      params.require(:project).permit(:name, :description,:user_id)
	    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
.well
  = form_for @project, html: { class: "form form-horizontal project" } do |f|
    .form-group
      %center
        .controls
          = f.text_field :name, class: 'form-control formElement', required: true, placeholder: 'Project name'
      = error_span(@project[:name])
    .form-group
      %center
        .controls
          = f.text_area :description, class: 'form-control formElement', required: true, placeholder: 'Project Description'
      = error_span(@project[:description])
    .form-group
      %center
        

    %center
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), projects_path, :class => 'btn btn-default'

app/views/projects/_members.html.haml
-if @users != nil
	= form_for :project, :url => {:action => "add_members", :id => @project} do |f|
		= fields_for(@member) do |m|
			.field
				%center
					= m.label "Add members"
					%br
					= collection_select(:user , :id , @users , :id , :username ,{})
					%br
					= f.submit "Add"

app/views/projects/comment.html.haml
%center
	.well.halfPageWidth
		%h1 Listing comments
		%table
			%thead
				%tr
					%th Project
					%th User Story
					%th comment
					
				%tbody
					- @comments.each do |comment|
						%tr
							%td
								=comment.project
							%td
								=comment.name
							%td
								=comment.content
							%br	

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/index.html.haml
%center
	.well.halfPageWidth
		= search_form_for @search do |f|
			= f.condition_fields do |c|
				.field
					= c.attribute_fields do |a|
						= a.attribute_select associations: [:users]
					= c.predicate_select
					=c.value_fields do |v|
						= v.text_field :value
			=f.submit "search" 


%h1
	Projects
%center
	.projectContainer
		- @projects.each do |project|
			%a{:href => "projects/#{project.id.to_s}"}
				.well= project.name
	
	= link_to 'New Project', new_project_path, :class => 'newProjectBtn btn btn-default'
	= button_to 'show comments', show_comments_path, method: :get ,:class => 'newProjectBtn btn btn-default'

	= form_tag comments_path  do
		= label_tag "Add members"	
		%br
		= collection_select(:user , :id , @users , :id , :username ,{})
		%br
		= submit_tag "show comments", :name => nil
	

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/show.html.haml
- model_class = Project
.page-header
	%h1
		-if @project.name.present?
			=@project.name
	
%center
	.well.halfPageWidth
		%p
			%strong= model_class.human_attribute_name(:name) + ':'
			= @project.name
		%p
			%strong= model_class.human_attribute_name(:description) + ':'
			= @project.description
		%p
			%strong User Stories:
			%br
			%ul
				- @project.user_stories.each do |story|
					%li
						%div
							%a{:href => "#{user_story_path(story.id)}"}
								=story.name
						%div
							= form_for story, url: changestate_path(story), html: { class: "form form-horizontal formElement",  remote: true } do |f|
								= f.select :state, ["to_be_do", "doing", "done"], class: 'form-control', required: true, placeholder: 'State'

		-if @owner_check == true
			= link_to 'Add User Story', 'user_stories/new/' + "#{@project.id}", :class => 'btn btn-default'
			= link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn btn-default'
			= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

		= link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn btn-default'
	.well.halfPageWidth
		%h5 All members: 
		-@all_members.each do |member|
			.media
				%a.pull-left
					%img.media-object.avatar{:src => "#{member.avatar.url(:thumb)}"}
				= member.username
			
	.well.halfPageWidth
		%h5 Add members 
		= form_tag project_path, :method => 'get' , :id => 'members_search' , remote: true do
			%p
			= text_field_tag :members_search, params[:members_search]
			= submit_tag "Search", :name => nil 

		#members
		=render('members')


		=link_to "Deliver" , deliver_path(:id => @project) 

app/views/projects/show.js.erb
//	alert("ahmed");
$("#members").html("<%= escape_javascript(render("members"))%>");

app/views/projects/show_comment.html.haml
%center
	.well.halfPageWidth
		%h1 Listing comments
		%table
			%thead
				%tr
					%th Project
					%th User Story
					%th Username
					%th comment
					%th task
					%th{:colspan => "3"}
				%tbody
					- @comments.each do |comment|
						%tr
							%td
								=comment.project
							%td
								=comment.name
							%td
								=comment.username
							%td
								=comment.content
							%td
								=comment.task
							%br	