config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tasks

  resources :user_stories do
    resources :user_story_files
  end 

  get 'projects/index'

  get 'projects/user_stories/show/:id' =>'user_stories#show'
  get 'projects/user_stories/new/:project_id' =>'user_stories#new'
  get 'productsjects/user_stories/show/tasks/:user_story_id' => 'tasks#new'
  get '/user_stories/tasks/:user_story_id' => 'tasks#new'

  patch '/user_stories/change_state/:id' => 'user_stories#changestate', as: "changestate" 

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :project_users
  resources :users
  resources :projects 
  root 'projects#index' , as: 'login'

  post 'projects/add_members' =>'projects#add_members'

  post 'user_stories/add_comment' =>'user_stories#add_comment' , as: 'add_comment'

  post 'project/comment' => 'projects#comment' , as: 'comments'

  get 'project/show_comments' => 'projects#show_comment' , as: 'show_comments'
  get 'project/deliver' => 'projects#deliver' , as: 'deliver'

end

app/models/user_story_file.rb
class UserStoryFile < ActiveRecord::Base
	has_attached_file :document, :default_url => "/files/missing.png"
  	validates_attachment_content_type :document, :content_type => 'text/plain'
  	belongs_to :user_story
end

app/controllers/user_story_files_controller.rb
class UserStoryFilesController < ApplicationController
  before_action :set_user_story_file, only: [:show, :edit, :update, :destroy]

  # GET /user_story_files
  # GET /user_story_files.json
  def index
    @user_story_files = UserStoryFile.all
  end

  # GET /user_story_files/1
  # GET /user_story_files/1.json
  def show
    
  end

  # GET /user_story_files/new
  def new
    @user_story = UserStory.find params[:user_story_id]
    @user_story_file = @user_story.user_story_files.new
  end

  # GET /user_story_files/1/edit
  def edit
  end

  # POST /user_story_files
  # POST /user_story_files.json
  def create
    @user_story = UserStory.find params[:user_story_id]; 
    @user_story_file = @user_story.user_story_files.build(user_story_file_params)
    # UserStoryFile.new(user_story_file_params) 

    respond_to do |format|
      if @user_story_file.save
        format.html { redirect_to user_story_path(@user_story), notice: 'User story file was successfully created.' }
        format.json { render :show, status: :created, location: @user_story_file }
      else
        format.html { render :new }
        format.json { render json: @user_story_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_story_files/1
  # PATCH/PUT /user_story_files/1.json
  def update
    respond_to do |format|
      if @user_story_file.update(user_story_file_params)
        format.html { redirect_to @user_story_file, notice: 'User story file was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_story_file }
      else
        format.html { render :edit }
        format.json { render json: @user_story_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_story_files/1
  # DELETE /user_story_files/1.json
  def destroy
    @user_story_file.destroy
    respond_to do |format|
      format.html { redirect_to user_story_files_url, notice: 'User story file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story_file
      @user_story_file = UserStoryFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_story_file_params
      params.require(:user_story_file).permit(:document)
    end
end

app/helpers/user_story_files_helper.rb
module UserStoryFilesHelper
end

app/views/user_story_files/_form.html.haml
= form_for @user_story_file, url: user_story_user_story_files_path(@user_story) do |f|
  - if @user_story_file.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_story_file.errors.count, "error")} prohibited this user_story_file from being saved:"
      %ul
        - @user_story_file.errors.full_messages.each do |msg|
          %li= msg
  = f.file_field :document 

  .actions
    = f.submit 'Save'

app/views/user_story_files/edit.html.haml
%h1 Editing user_story_file

= render 'form'

= link_to 'Show', @user_story_file
\|
= link_to 'Back', user_story_files_path

app/views/user_story_files/index.html.haml
%h1 Listing user_story_files

%table
  %tr
    %th
    %th
    %th

  - @user_story_files.each do |user_story_file|
    %tr
      %td= link_to 'Show', user_story_user_story_files_path
      %td= link_to 'Edit', edit_user_story_user_story_file_path(params[:user_story_id], user_story_file)
      %td= link_to 'Destroy', user_story_user_story_file_path(params[:user_story_id], user_story_file), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User story file', new_user_story_user_story_file_path(params[:user_story_id])

app/views/user_story_files/new.html.haml
%h1 New user_story_file

= render 'form'

= link_to 'Back', user_story_user_story_files_path(@user_story)

app/views/user_story_files/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_story_file_path(@user_story_file)
\|
= link_to 'Back', user_story_files_path